### ISSUE TITLE
Kernel not supported 6.5.0-valve22-1-neptune-65-g9a338ed8a75e

### ISSUE THREAD

**Issue by kramlat** [ryanrudolfoba/SteamOS-Waydroid-Installer#173] opened 2024-10-24 06:19 UTC
please send me the binder source and I will build it myself. Otherwise, I hope the module will be ready. SteamOS 3.6 stable has released.

**Comment by ryanrudolfoba** [comment] 2024-10-25 12:55
duplicate of - https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/171

**Closed by ryanrudolfoba** 2024-10-25 12:55 UTC

**Comment by ryanrudolfoba** [comment] 2024-10-28 18:49
**If you used the cloned repo then it doesnt have my latest fixes / enhancements.**

SteamOS Waydroid Installer Script has been updated!

What's New (as of Oct 28 2024)
1. Support for latest SteamOS Stable 3.6.19
2. fixed binder kernel module parameters
3. enhancement - ability to choose with / without Google Playstore on a fresh install
4. enhancement - automatically activate mantis gamepad pro and shizuku
5. enhancement - disable root detection (some apps might still detect root)
6. enhancement - disable first time setup wizard
7. enhancement - Waydroid Toolbox - added NETWORK option
8. enhanceement - Waydroid Toolbox - updated ADBLOCK option

This can also be used as an install guide! Make sure you have a sudo password already set and then do the konsole commands!

Moving forward just do the Waydroid-Updater.sh to easily clone and install the latest version of the script!

Upgrade guide here -
https://youtu.be/CJAMwIb_oI0

Happy gaming!

-10MinuteSteamDeckGamer
