### ISSUE TITLE
Kernel not supported 

### ISSUE THREAD

**Issue by d3vC0mm4nd3rShadowSlayer29** [ryanrudolfoba/SteamOS-Waydroid-Installer#171] opened 2024-10-19 03:52 UTC
Good day,

My steamdeck unable to install the Waydroid due to incompatibility

I have updated this on the latest official update of Steam, well in beta release but this is the error I have encountered.

From Termnial
"
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
6.5.0-valve21-1-neptune-65 is NOT supported. Exiting immediately.
"

From Steam System Information
"
Operating System Version:
"SteamOS Holo" (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.0-valve21-1-neptune-65-g33487bf05ed3
X Server Vendor: The X.Org Foundation
X Server Release: 12101011
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240916.101793
"

**Comment by ryanrudolfoba** [comment] 2024-10-19 04:19
Make sure to clone the repo to get the latest version of the script. I've updated this about a week ago to support the latest SteamOS beta.

**Comment by d3vC0mm4nd3rShadowSlayer29** [comment] 2024-10-21 01:14
Okie dokie. Will perform the steps as per your instructions. Will provide you updates in a bit. I might have missed a step or two while executing the script.

I'll try to uninstall it first as it might have caused the error.

**Comment by Blood-PawWerewolf** [comment] 2024-10-24 02:40
can confirm that i'm getting this as well. re-cloned the repo and still fails

**Comment by ryanrudolfoba** [comment] 2024-10-24 02:47
> can confirm that i'm getting this as well. re-cloned the repo and still fails.
> 
> oh! it's definitely not supported: "6.5.0-valve22-1-neptune-65, SteamOS 3.6.19"
> 
> there was a system update today so whatever you did no longer works

Thats because of the latest stable update released a few hours ago. I'll rebuild the appropriate kernel module tomorrow

**Comment by MotownM** [comment] 2024-10-26 07:10
Greetings. I'm having this same exact issue. (Checking if kernel is supported. 6.5.0-valve21-1-neptune-65 is NOT supported. Exiting immediately.) Are there any updates on this?

**Comment by Tauum** [comment] 2024-10-26 11:17
Same issue here

**Comment by tylerjwoodfin** [comment] 2024-10-27 07:05
Still seeing this. Thanks!

**Comment by KsAmJ** [comment] 2024-10-27 16:24
Where is the fix?

**Comment by WhiteGh05t** [comment] 2024-10-27 20:03
The fix will come when it comes. Who knows, he may have run into some issues or have more important things in life. I'm just thankful that he is looking into it.

**Comment by Taboulet** [comment] 2024-10-27 20:05
The dev is back, he just close a duplicate of this issue. So its soon we just have to wait a lil bit

**Comment by ryanrudolfoba** [comment] 2024-10-28 00:43
sorry for delay been adding stuff / enhancement requests and doing code cleanup too.

**Comment by MotownM** [comment] 2024-10-28 00:51
> sorry for delay been adding stuff / enhancement requests and doing code cleanup too.

Thank you for your service. We appreciate you.

**Comment by tylerjwoodfin** [comment] 2024-10-28 00:53
^ This, open source is often a thankless job. I can't wait to try this out on my Steam Deck, and thank you for actively maintaining something so beneficial for the community!

**Comment by MotownM** [comment] 2024-10-28 01:00
> ^ This, open source is often a thankless job. I can't wait to try this out on my Steam Deck, and thank you for actively maintaining something so beneficial for the community!

You are very welcome. Your source is the most valuable program on my Steam Deck. I was devasted when it wouldn't open, and I'm grateful you're proactive—much love.

**Comment by pizzadude** [comment] 2024-10-28 05:56
Just build the module yourself. Not gonna spoonfeed, but you can take a look at this: https://github.com/pizzadude/SteamOS-Waydroid-Installer.custom/blob/main/build-binder-headers.sh

**Comment by JGannon-Aspen** [comment] 2024-10-28 14:16
> Just build the module yourself. Not gonna spoonfeed, but you can take a look at this: https://github.com/pizzadude/SteamOS-Waydroid-Installer.custom/blob/main/build-binder-headers.sh

For anyone else having issues, this helped me workaround the issue.

I simply cloned pizzadude's fork and ran the build-binder-headers.sh script he referenced, and then I was able to run the normal installer script.

I'm guessing this repo will probably be updated soon to work out of the box as well, for those that want to wait.  Thanks to everyone involved in this installer.  Having waydroid on the deck is awesome.

**Comment by ryanrudolfoba** [comment] 2024-10-28 14:34
Thanks guys for taking over i appreciate it!

**Comment by smabbage** [comment] 2024-10-28 15:09
Worked like a champ mrvictory1!  Thanks.

**Comment by Steamdeckguy** [comment] 2024-10-28 16:18
guys, im really new to linux and cant solve this issue, can anyone help me please?

**Comment by smabbage** [comment] 2024-10-28 16:36
Instead of cloning Ryan's github, you clone mrvictory1's github and follow the same installation instructions.

clone http://github.com/mrvictory1/SteamOS-Waydroid-Installer

**Comment by Steamdeckguy** [comment] 2024-10-28 16:37
oh, that's all? thank you

**Comment by ryanrudolfoba** [comment] 2024-10-28 18:48
**If you used the cloned repo then it doesnt have my latest fixes / enhancements.**

SteamOS Waydroid Installer Script has been updated!

What's New (as of Oct 28 2024)
1. Support for latest SteamOS Stable 3.6.19
2. fixed binder kernel module parameters
3. enhancement - ability to choose with / without Google Playstore on a fresh install
4. enhancement - automatically activate mantis gamepad pro and shizuku
5. enhancement - disable root detection (some apps might still detect root)
6. enhancement - disable first time setup wizard
7. enhancement - Waydroid Toolbox - added NETWORK option
8. enhanceement - Waydroid Toolbox - updated ADBLOCK option

This can also be used as an install guide! Make sure you have a sudo password already set and then do the konsole commands!

Moving forward just do the Waydroid-Updater.sh to easily clone and install the latest version of the script!

Upgrade guide here -
https://youtu.be/CJAMwIb_oI0

Happy gaming!

-10MinuteSteamDeckGamer

**Closed by ryanrudolfoba** 2024-10-28 18:48 UTC

**Comment by Steamdeckguy** [comment] 2024-10-28 19:11
and it says that the script on the original one was updated but it still showed the same error

**Comment by ryanrudolfoba** [comment] 2024-10-28 19:29
> and it says that the script on the original one was updated but it still showed the same error

Which step are you following? Which commands are you using?

**Comment by Steamdeckguy** [comment] 2024-10-28 19:33
Go into Desktop Mode and open a konsole terminal.
Clone the github repo.
cd ~/
git clone https://github.com/ryanrudolfoba/steamos-waydroid-installer
Execute the script!
cd ~/steamos-waydroid-installer
chmod +x steamos-waydroid-installer.sh
./steamos-waydroid-installer.sh

**Comment by ryanrudolfoba** [comment] 2024-10-28 19:42
Try using the new guide via Waydroid-Updater.sh

Let me know how it goes

**Comment by Steamdeckguy** [comment] 2024-10-28 19:45
or can you please tell me the commands i need to put? i didn't really understand what i needed to do

**Comment by Steamdeckguy** [comment] 2024-10-28 19:45
and btw thanks for the quick response time and your patience

**Comment by ryanrudolfoba** [comment] 2024-10-28 20:01
Here -

cd ~/

wget https://raw.githubusercontent.com/ryanrudolfoba/SteamOS-Waydroid-Installer/refs/heads/main/extras/Waydroid-Updater.sh -O ~/Waydroid-Updater.sh

chmod +x Waydroid-Updater.sh

./Waydroid-Updater.sh

And moving forward if there is an update just run the last command -

./Waydroid-Updater.sh

But really i would suggest to take a quick peak on the accompanying upgrade guide video.

**Comment by Tauum** [comment] 2024-10-28 20:12
Now i can install. But it does not generate a steam shortcut, opening in desktop-mode closes straight away and there is no uninstall script available as others have described.

**Comment by ryanrudolfoba** [comment] 2024-10-28 20:16
> Now i can install. But it does not generate a steam shortcut, opening in desktop-mode closes straight away and there is no uninstall script available as others have described.

What method did you use? I would suggest the Waydroid-Updater.sh method.

**Comment by Steamdeckguy** [comment] 2024-10-28 20:34
uhm, one problem, it says this![image](https://github.com/user-attachments/assets/2a47e277-8357-4e57-b2da-d3b39b1c687b)

**Comment by Steamdeckguy** [comment] 2024-10-28 20:45
nvm it just started working rn
