### ISSUE TITLE
Can't install waydroid in steamos 3.6.20

### ISSUE THREAD

**Issue by bob448** [ryanrudolfoba/SteamOS-Waydroid-Installer#196] opened 2024-12-15 21:25 UTC
Yep

```
SteamOS Waydroid Installer Script by ryanrudolf
https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer
YT - 10MinuteSteamDeckGamer
Script is running in Desktop Mode.
Checking if kernel is supported.
SteamOS 3.6.20 - kernel version 6.5.0-valve23-1-neptune-65 is NOT supported. Exiting immediately.
```

**Comment by ryanrudolfoba** [comment] 2024-12-15 21:43
That looks like the latest beta released a few days ago. This will need an update to the binder kernel module.

**Comment by agilgur5** [comment] 2024-12-24 19:18
Duplicate of #194

**Comment by ryanrudolfoba** [comment] 2024-12-27 16:21
this is a duplicate of https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/194

i'll build the kernel module soon

**Closed by ryanrudolfoba** 2024-12-27 16:21 UTC

**Comment by ryanrudolfoba** [comment] 2024-12-27 19:43
script has been updated to support latest SteamOS 3.6.21 beta

![image](https://github.com/user-attachments/assets/9d840318-5553-4417-9182-2f581692623d)
