### ISSUE TITLE
Controller input not detected no matter what

### ISSUE THREAD

**Issue by ANGER2077** [ryanrudolfoba/SteamOS-Waydroid-Installer#91] opened 2024-06-01 09:40 UTC
Title says everything. I've tried using the controller layout and it refuses to work no matter what, but keyboard inputs do work???

**Comment by ANGER2077** [comment] 2024-07-08 00:01
I've figured out how to fix it! Just switch to the keyboard layout on the steam controller layout thing, and move the dpad a bit, then switch back to the controller layout. weird fix but whatever

**Comment by ANGER2077** [comment] 2024-07-08 00:08
nevermind now its not working what the hell

**Comment by CmdrJorgs** [comment] 2024-07-08 23:43
Same issue with unresponsive controller inputs, only keyboard and touch inputs work. Closing out Waydroid and re-opening does not resolve the issue.

**Comment by baghera8** [comment] 2024-07-09 21:28
Having the same issue on the latest Steam client (Stable, OS 3.5.19).

**Comment by JBLICERIO** [comment] 2024-08-07 02:58
Same issue here. At first launch everything is working even using the game controller works. controller detection works but when you close waydroid and re-open it the controller wont work anymore. no matter what you do. i dont know what im doing wrong. tried to reinstall waydroid with same procedure but the problem is the same it only works at initial launch. succeding launch of waydroid eliminates the use of steam deck controller.

**Comment by ANGER2077** [comment] 2024-08-11 08:45
I've figured out the issue on my end, for some reason having my bluetooth ear buds connected breaks controller input, but ONLY if i connect them while waydroid is launched. having the ear buds connected before waydroid is launched doesnt break anything

**Comment by JBLICERIO** [comment] 2024-08-16 02:17
> I've figured out the issue on my end, for some reason having my bluetooth ear buds connected breaks controller input, but ONLY if i connect them while waydroid is launched. having the ear buds connected before waydroid is launched doesnt break anything

This is true for me too. when there is a connected bluetooth device the steam deck controller breaks. when there is no bluetooth device connected the controller detection works flawlessly. i will try the suggestion above, connecting before waydroid launch.

**Comment by JBLICERIO** [comment] 2024-08-16 13:35
> > I've figured out the issue on my end, for some reason having my bluetooth ear buds connected breaks controller input, but ONLY if i connect them while waydroid is launched. having the ear buds connected before waydroid is launched doesnt break anything
> 
> This is true for me too. when there is a connected bluetooth device the steam deck controller breaks. when there is no bluetooth device connected the controller detection works flawlessly. i will try the suggestion above, connecting before waydroid launch.

i can now confirm that the culprit in controller not detected is the blutooth. when you have devices connected to bluetooth prior to launching waydroid, the controller wont be detected. but when there's nothing connected to bluetooth prior to launching waydroid the contoller is working. so the solution for now is launch waydroid first before connecting any bluetooth devices. This works for me atleast, hopefully it will be fixed in the future. this may not be the case to others but this is what i figured out on my SD. hopefully this helped others with same case as mine.😃

**Comment by baghera8** [comment] 2024-08-17 02:05
Thanks for the updates, guys.
Unfortunately, no amount of Bluetooth tweaking resolved the issue for me. I've tried having a device connected before Waydroid launch, NOT having a device connected, having Bluetooth off, etc. I've just installed the latest beta channel update which has a few Steam Input related fixes. The SteamOS-Waydroid-Installer doesn't yet support the latest beta kernel, but once it does, I'll give it another shot, and hopefully the latest beta does the trick. 🤞🏻

**Comment by ryanrudolfoba** [comment] 2024-08-17 02:17
3.6.10 beta is supported - I've updated the script yesterday.

Make sure clone the repo again to get the latest version and perform the install.

![Screenshot_20240816-221704](https://github.com/user-attachments/assets/06b71a99-e344-4848-b357-cf5cf3f1cf98)

**Comment by baghera8** [comment] 2024-08-17 02:46
Yes! Thank you! I just realized it an hour ago when browsing through the recent github issues.
Unfortunately, neither the reinstall, nor the latest Waydroid (internal) updates resolved the controller issue for me. 🤷🏻

**Comment by KoTeYkA23** [comment] 2024-11-25 07:49
> I've figured out how to fix it! Just switch to the keyboard layout on the steam controller layout thing, and move the dpad a bit, then switch back to the controller layout. weird fix but whatever

That is actually helped me rn, but yeah after some point when relaunching waydroid controller is stopped working. Have the old LCD version with mhda controller version

**Comment by KoTeYkA23** [comment] 2024-11-25 07:55
> That is actually helped me rn
Steps to fix: save your normal waydroid layout (do it 1 time), launch waydroid, change layout to WASD + Mouse, back to waydroid and click dpad couple times, if apps in launcher selecting now change back your old layout for waydroid and now controller suddenly working.

**Comment by baghera8** [comment] 2024-11-25 17:02
Thanks, @KoTeYkA23 and @ANGER2077 ! 
The fix is working great now, despite not having worked for me back in July. 🤷🏻
I FINALLY have gamepad input in Waydroid on my Deck! Time to cook! 😁

**Comment by KoTeYkA23** [comment] 2024-11-25 17:10
Interestingly enough that even when gamepad is not working its not detecting by any gamepad program, but it shows up in devices list in AIDA64, so I suspect it could be android driver problem or it's android bug itself (I'm not drivers developer, just speculating).

**Comment by ryanrudolfoba** [comment] 2024-12-06 19:28
i've updated the script so that the delay timeout for controller detection is more accurate.

check if that fixes controller issue.

**Comment by KoTeYkA23** [comment] 2024-12-09 19:41
> i've updated the script so that the delay timeout for controller detection is more accurate.

Seems to be working perfectly now, at least 3 times in a row controller picked up perfectly, thanks for your amazing work!

**Comment by KoTeYkA23** [comment] 2024-12-10 06:17
Found interesting bug, if you connect bluetooth headphones controller won't work on launch, switching layout trick still fixing it. Without headphones seems to work properly.

**Comment by ryanrudolfoba** [comment] 2024-12-10 16:34
i'll be closing this and mention the workarounds in the README when using bluetooth headphones. thank you for the feedback.

**Closed by ryanrudolfoba** 2024-12-10 16:34 UTC
