### ISSUE TITLE
Not supported 

### ISSUE THREAD

**Issue by Kotovgihubr** [ryanrudolfoba/SteamOS-Waydroid-Installer#175] opened 2024-10-26 14:09 UTC
6.5.0-valve22-1-neptune-65 is NOT supported

**Comment by Kotovgihubr** [comment] 2024-10-26 14:10
Pls fix

**Comment by Taboulet** [comment] 2024-10-26 18:59
Check https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/171 for more info, but in short it will soon be fixed

**Comment by ryanrudolfoba** [comment] 2024-10-27 19:40
Duplicate of https://github.com/ryanrudolfoba/SteamOS-Waydroid-Installer/issues/171

**Closed** 2024-10-27 19:40 UTC
